export interface BundeslandInfo {
  code: string
  name: string
  capital: string
  population: string
  areaKm2: string
  icon: string
  description: string
  // Curated regional summary metrics
  hotDaysAvg: number // Heiße Tage (Tmax >= 30 °C) pro Jahr (2018-2025)
  allTimeRecord: { temp: number; year: number; location: string }
  windCapacityMw: number // Installierte MW Windkraft (MaStR)
  solarCapacityMw: number // Installierte MW Solar (MaStR)
  prtrEmissionsKt: number // Gemeldete PRTR-Industrie-Emissionen (kt/Jahr)
  highlights: string[]
}

export const BUNDESLAENDER: Record<string, BundeslandInfo> = {
  BW: {
    code: 'BW',
    name: 'Baden-Württemberg',
    capital: 'Stuttgart',
    population: '11,3 Mio.',
    areaKm2: '35.751 km²',
    icon: '🏰',
    description: 'Oberrheingraben als Hitze-Hotspot; starker Ausbau von PV und Wasserkraft.',
    hotDaysAvg: 18.4,
    allTimeRecord: { temp: 40.2, year: 2003, location: 'Freiburg' },
    windCapacityMw: 1850,
    solarCapacityMw: 9400,
    prtrEmissionsKt: 14.2,
    highlights: [
      'Oberrheingraben gehört zu den wärmsten Regionen Deutschlands',
      'Hohes Solar-Potenzial auf Wohn- und Gewerbedächern',
      'Beteiligung an mehreren Wasserkraft- und Geothermieprojekten',
    ],
  },
  BY: {
    code: 'BY',
    name: 'Bayern',
    capital: 'München',
    population: '13,4 Mio.',
    areaKm2: '70.550 km²',
    icon: '🏔️',
    description: 'Führend bei Photovoltaik & Biomasse; starker Solar-Boom auf Freiflächen.',
    hotDaysAvg: 14.8,
    allTimeRecord: { temp: 40.3, year: 2015, location: 'Kitzingen' },
    windCapacityMw: 2650,
    solarCapacityMw: 21500,
    prtrEmissionsKt: 18.6,
    highlights: [
      'Größte installierte Solar-Kapazität aller Bundesländer (> 21 GW)',
      'Hohe Dichte an Freiflächen-Solarparks und Biogasanlagen',
      'Alpenvorland zeigt deutliche Temperatur- und Abflussveränderungen',
    ],
  },
  BE: {
    code: 'BE',
    name: 'Berlin',
    capital: 'Berlin',
    population: '3,8 Mio.',
    areaKm2: '891 km²',
    icon: '🏛️',
    description: 'Städtische Wärmeinsel mit starkem Ausbaudruck für Gründächer & Solar.',
    hotDaysAvg: 19.2,
    allTimeRecord: { temp: 38.9, year: 2019, location: 'Berlin-Kaniswall' },
    windCapacityMw: 25,
    solarCapacityMw: 320,
    prtrEmissionsKt: 4.8,
    highlights: [
      'Ausgeprägter Urban Heat Island Effekt (Hitzeinsel in Innenstädten)',
      'Solar-Pflicht für Neubauten und Dachsanierungen',
      'Umfassender Hitzeaktionsplan für den Schutz verletzlicher Gruppen',
    ],
  },
  BB: {
    code: 'BB',
    name: 'Brandenburg',
    capital: 'Potsdam',
    population: '2,6 Mio.',
    areaKm2: '29.654 km²',
    icon: '🌲',
    description: 'Pionierland bei Windkraft; hohe Sommertemperaturen & Waldbrandrisiko.',
    hotDaysAvg: 19.8,
    allTimeRecord: { temp: 39.2, year: 2019, location: 'Cottbus' },
    windCapacityMw: 8800,
    solarCapacityMw: 6700,
    prtrEmissionsKt: 22.4,
    highlights: [
      'Einer der höchsten Erneuerbare-Energien-Anteile an der Stromerzeugung',
      'Große Flächen für Windparks an Land und Agro-Photovoltaik',
      'Erhöhtes Risiko für Sommertrockenheit und Waldbrände',
    ],
  },
  HB: {
    code: 'HB',
    name: 'Bremen',
    capital: 'Bremen',
    population: '0,68 Mio.',
    areaKm2: '419 km²',
    icon: '⚓',
    description: 'Hafen- & Industriestandort mit Fokus auf Windenergie-Logistik und Dekarbonisierung.',
    hotDaysAvg: 11.2,
    allTimeRecord: { temp: 37.6, year: 2022, location: 'Bremen' },
    windCapacityMw: 210,
    solarCapacityMw: 180,
    prtrEmissionsKt: 6.1,
    highlights: [
      'Zentrum für Offshore-Windenergie-Logistik und Forschung',
      'Transformation der Stahlindustrie hin zu grünem Wasserstoff',
      'Küstenschutz und Sturmflutvorsorge im Mündungsgebiet der Weser',
    ],
  },
  HH: {
    code: 'HH',
    name: 'Hamburg',
    capital: 'Hamburg',
    population: '1,9 Mio.',
    areaKm2: '755 km²',
    icon: '🚢',
    description: 'Maritime Energiewende; Wasserstoff-Hub und städtischer Klimaschutz.',
    hotDaysAvg: 12.1,
    allTimeRecord: { temp: 40.1, year: 2022, location: 'Hamburg-Neuwiedenthal' },
    windCapacityMw: 130,
    solarCapacityMw: 290,
    prtrEmissionsKt: 7.9,
    highlights: [
      'Historischer Temperaturrekord von 40,1 °C im Juli 2022',
      'Wasserstoffnetz im Hamburger Hafen zur Industrie-Dekarbonisierung',
      'Gründach- und Fassadenbegrünungs-Förderung gegen Hitzeinseln',
    ],
  },
  HE: {
    code: 'HE',
    name: 'Hessen',
    capital: 'Wiesbaden',
    population: '6,4 Mio.',
    areaKm2: '21.115 km²',
    icon: '🌳',
    description: 'Waldreiches Bundesland mit hoher Hitzebelastung im Rhein-Main-Gebiet.',
    hotDaysAvg: 16.9,
    allTimeRecord: { temp: 40.2, year: 2019, location: 'Westend / Frankfurt' },
    windCapacityMw: 2550,
    solarCapacityMw: 3600,
    prtrEmissionsKt: 11.8,
    highlights: [
      'Rhein-Main-Verdichtungsraum stark von Sommertropennächten betroffen',
      'Große Waldbrand- Vorsorgeprogramme in den Waldgebieten des Taunus/Spessart',
      'Steigende Investitionen in technischen und naturnahen Hochwasserschutz',
    ],
  },
  MV: {
    code: 'MV',
    name: 'Mecklenburg-Vorpommern',
    capital: 'Schwerin',
    population: '1,6 Mio.',
    areaKm2: '23.211 km²',
    icon: '🌊',
    description: 'Wind- & Ostsee-Pionier; hohe Pro-Kopf-Erzeugung an grünem Strom.',
    hotDaysAvg: 9.8,
    allTimeRecord: { temp: 39.4, year: 2022, location: 'Boizenburg' },
    windCapacityMw: 7400,
    solarCapacityMw: 3900,
    prtrEmissionsKt: 3.4,
    highlights: [
      'Erzeugt ein Vielfaches seines eigenen Strombedarfs aus Erneuerbaren',
      'Bedeutender Standort für Offshore- und Onshore-Windenergie',
      'Küstenschutzprojekte an Ostsee und Boddenlandschaften',
    ],
  },
  NI: {
    code: 'NI',
    name: 'Niedersachsen',
    capital: 'Hannover',
    population: '8,1 Mio.',
    areaKm2: '47.614 km²',
    icon: '🌾',
    description: 'Windenergie-Spitzenreiter Deutschlands; starker Agrarsektor & Küstenschutz.',
    hotDaysAvg: 13.5,
    allTimeRecord: { temp: 40.0, year: 2022, location: 'Lingen' },
    windCapacityMw: 12900,
    solarCapacityMw: 7800,
    prtrEmissionsKt: 21.5,
    highlights: [
      'Absoluter Windkraft-Spitzenreiter in Deutschland (> 12,9 GW installierte Leistung)',
      'Wichtige Rolle beim Netzausbau (SuedLink, SuedOstLink)',
      'Landwirtschaftlicher Fokus auf Reduzierung des Stickstoffüberschusses',
    ],
  },
  NW: {
    code: 'NW',
    name: 'Nordrhein-Westfalen',
    capital: 'Düsseldorf',
    population: '18,1 Mio.',
    areaKm2: '34.110 km²',
    icon: '🏭',
    description: 'Industrie- & Bevölkerungsschwerpunkt; massiver Wandel von Kohle zu Erneuerbaren.',
    hotDaysAvg: 17.6,
    allTimeRecord: { temp: 41.2, year: 2019, location: 'Duisburg / Tönisvorst' },
    windCapacityMw: 7100,
    solarCapacityMw: 10200,
    prtrEmissionsKt: 48.5,
    highlights: [
      'Größter PRTR-Industrie-Emittent Deutschlands (Ruhrgebiet & Rheinschiene)',
      'Beschleunigter Ausbau von Dach-Solar und Windkraft auf Industrieflächen',
      'Klimaanpassungsgesetz als Vorreiter für kommunale Ausbaupläne',
    ],
  },
  RP: {
    code: 'RP',
    name: 'Rheinland-Pfalz',
    capital: 'Mainz',
    population: '4,2 Mio.',
    areaKm2: '19.854 km²',
    icon: '🍷',
    description: 'Weinbau & Waldreich; Starkregen-Vorsorge im Ahrtal & Moselgebiet.',
    hotDaysAvg: 17.8,
    allTimeRecord: { temp: 40.4, year: 2019, location: 'Andernach' },
    windCapacityMw: 3950,
    solarCapacityMw: 4100,
    prtrEmissionsKt: 8.9,
    highlights: [
      'Veränderte Reifezeiten im Weinbau durch verfrühte Phänologie-Phasen',
      'Umfassende Neuausrichtung des kommunalen Hochwasser- & Starkregenschutzes',
      'Starker Ausbau von Bürger-Energiegenossenschaften',
    ],
  },
  SL: {
    code: 'SL',
    name: 'Saarland',
    capital: 'Saarbrücken',
    population: '0,99 Mio.',
    areaKm2: '2.570 km²',
    icon: '⚒️',
    description: 'Stahl- & Industrieregion im Grünen Wasserstoff-Umbau.',
    hotDaysAvg: 16.5,
    allTimeRecord: { temp: 40.2, year: 2003, location: 'Nennig' },
    windCapacityMw: 540,
    solarCapacityMw: 890,
    prtrEmissionsKt: 6.8,
    highlights: [
      'Transformation der Traditions-Stahlwerke hin zu Wasserstoff-Direktreduktion',
      'Hohe Waldfläche schützt vor lokaler Überhitzung',
      'Grenzüberschreitende Klimaprojekte mit Frankreich und Luxemburg',
    ],
  },
  SN: {
    code: 'SN',
    name: 'Sachsen',
    capital: 'Dresden',
    population: '4,1 Mio.',
    areaKm2: '18.420 km²',
    icon: '🏰',
    description: 'Lausitz im Strukturwandel; Halbleiter-Boom & Solar-Ausbau.',
    hotDaysAvg: 18.9,
    allTimeRecord: { temp: 39.8, year: 2019, location: 'Dresden-Hosterwitz' },
    windCapacityMw: 1310,
    solarCapacityMw: 3400,
    prtrEmissionsKt: 19.3,
    highlights: [
      'Strukturwandel im Lausitzer Braunkohlerevier hin zu Solar-Großparks',
      'High-Tech-Standort Silicon Saxony mit hohen Effizienzstandards',
      'Elbe-Hochwasserschutz nach den historischen Fluten ausgebaut',
    ],
  },
  ST: {
    code: 'ST',
    name: 'Sachsen-Anhalt',
    capital: 'Magdeburg',
    population: '2,2 Mio.',
    areaKm2: '20.459 km²',
    icon: '🌪️',
    description: 'Sehr hoher Anteil erneuerbaren Stroms; Chemiepark-Transformation.',
    hotDaysAvg: 18.5,
    allTimeRecord: { temp: 39.6, year: 2019, location: 'Bernburg' },
    windCapacityMw: 5400,
    solarCapacityMw: 4200,
    prtrEmissionsKt: 15.7,
    highlights: [
      'Hoher Erneuerbare-Energien-Deckungsanteil am Stromverbrauch',
      'Chemiepark Leuna & Bitterfeld im Umbau auf grüne Rohstoffe',
      'Trockene Börde-Böden erfordern nachhaltige Agrar-Bewässerung',
    ],
  },
  SH: {
    code: 'SH',
    name: 'Schleswig-Holstein',
    capital: 'Kiel',
    population: '2,9 Mio.',
    areaKm2: '15.804 km²',
    icon: '🌬️',
    description: 'Land zwischen den Meeren; Vorreiter bei Windenergie & Stromexport.',
    hotDaysAvg: 7.9,
    allTimeRecord: { temp: 39.1, year: 2022, location: 'Grambek' },
    windCapacityMw: 8500,
    solarCapacityMw: 3600,
    prtrEmissionsKt: 3.1,
    highlights: [
      'Niedrigste Hitzebelastung in Deutschland dank kühler Meeresbrisen',
      'Ziel von 100 % erneuerbarer Stromdeckung längst überschritten',
      'Umfassende Deichbau- und Küstenschutz-Investitionen für die Zukunft',
    ],
  },
  TH: {
    code: 'TH',
    name: 'Thüringen',
    capital: 'Erfurt',
    population: '2,1 Mio.',
    areaKm2: '16.202 km²',
    icon: '🌲',
    description: 'Grünes Herz Deutschlands; Waldumbau im Thüringer Wald & PV-Wachstum.',
    hotDaysAvg: 16.1,
    allTimeRecord: { temp: 38.6, year: 2019, location: 'Jena' },
    windCapacityMw: 1850,
    solarCapacityMw: 2600,
    prtrEmissionsKt: 5.2,
    highlights: [
      'Große Waldumbau-Initiativen nach Borkenkäfer- und Trockenschäden',
      'Wachsende Solarnutzung in Tälern und Gewerbegebieten',
      'Forschung an nachhaltiger Forst- und Landwirtschaft an der Uni Jena',
    ],
  },
}
